name: davi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: davi
      run: |
        cp -R P:\Sem Backup\Colaboradores\Davi\Teste\Daelly-Software